CREATE TABLE IF NOT EXISTS USER (
  ID                INTEGER   PRIMARY KEY AUTOINCREMENT,
  USERNAME          TEXT      NOT NULL,
  PASSWORDHASH      TEXT      NOT NULL,
  FAILEDLOGINCOUNT  INTEGER,
  REMAININGLOGINS   INTEGER
);
